### ISSUE TITLE
Milestone Alerts for attendance

### ISSUE THREAD

**Issue by Logan9312** [CMPUT301W24T30/ScanPal#22]
### Issue Description
"As an organizer, I want to track real-time attendance and receive alerts for important milestones."
Must integrate existing features along side new ones such that, from the organizers  Point of view on their event's details, they can go to the organizers menu to, view the current attendees, in addition the organizer must receive push notifications about the amount of attendees signed up and  checked in(increments of 5 then 10?, notifications for 1st, 5,10,15,20, 30 and then 40 attendees)

## Acceptance Criteria:
 - [x]  Integrate the 'Organizer Options' menu
 - [x]  the milestones should pop up when app is in background
 - [x] Fix Check in count

## Notes:
 Will have to change the UI a bit in Events details page to accommodate organizers sending announcements
User and event Controllers will be altered

Organizer Options should so far consist of options to:
Edit event
send announcement
View attendees
View map 
show check in QR
show QR for event details
